#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# Activate VirtualEnv in order to use the correct libraries
if [ ! -d "$OPENSHIFT_DATA_DIR"/media ]; then
echo "Executing 'python mkdir $OPENSHIFT_DATA_DIR/media'"
mkdir "$OPENSHIFT_DATA_DIR"media
fi

if [ ! -d "$OPENSHIFT_REPO_DIR"wsgi/static/media ]; then
echo "Executing 'python mkdir $OPENSHIFT_REPO_DIRwsgi/static/media'"
mkdir "$OPENSHIFT_REPO_DIR"wsgi/static
mkdir "$OPENSHIFT_REPO_DIR"wsgi/static/media
fi

echo "Executing 'python ln -sf $OPENSHIFT_DATA_DIR/media $OPENSHIFT_REPO_DIR/wsgi/static/media'"
ln -sf "$OPENSHIFT_DATA_DIR"media "$OPENSHIFT_REPO_DIR"wsgi/static/media