#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

echo "Executing 'python ln -sf $OPENSHIFT_DATA_DIR/media $OPENSHIFT_REPO_DIR/wsgi/static/media'"
if [ ! -d $OPENSHIFT_DATA_DIR/media ]; then
mkdir $OPENSHIFT_DATA_DIR/media
fi
 
ln -sf $OPENSHIFT_DATA_DIR/media $OPENSHIFT_REPO_DIR/wsgi/static/media

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/project/manage.py migrate --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/project/manage.py migrate --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/project/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/project/manage.py collectstatic --noinput